CREATE DATABASE IF NOT EXISTS ecommerce;

CREATE TABLE public.users (
	active bool NOT NULL,
	id int8 NOT NULL,
	email varchar(255) NULL,
	"password" varchar(255) NULL,
	"role" varchar(255) NULL,
	username varchar(255) NULL,
	CONSTRAINT users_pkey null
);

CREATE TABLE public.products (
	price float8 NULL,
	id int8 NOT NULL,
	description varchar(255) NULL,
	"name" varchar(255) NULL
);

CREATE TABLE public.orders (
	is_random_order bool NULL,
	total float8 NULL,
	"date" timestamp(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	user_id int8 NULL,
	CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE public.order_details (
	quantity int4 NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	order_id int8 NULL,
	product_id int8 NULL
);

CREATE TABLE public.inventory (
	stock int4 NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	product_id int8 NOT NULL,
	CONSTRAINT inventory_pkey PRIMARY KEY (id),
	CONSTRAINT inventory_product_id_key UNIQUE (product_id)
);